[package]
name = "rss-client-rust"
version = "0.1.0"
edition = "2021"

[profile.release]
opt-level = "z" 
lto = true
codegen-units = 1
panic = "abort"
strip = true

[dependencies]
serde = "1.0.145"
serde_derive = "1.0.145"
toml = "0.5.9"
