[[categories]]
name = "youtube"
sprawl = false
aliases = ["yt"]

[[feeds]]
category = "youtube"
url  = "https://www.youtube.com/feeds/videos.xml?channel_id=UCLA_DiR1FfKNvjuUpBHmylQ"
name = "nasa"
aliases = []
